### ISSUE TITLE
link not found

### ISSUE THREAD

**Issue by billowqiu** [dubbo/dubbo-rpc-native-thrift#13]
https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-thrift
这个页面404了。。

**Comment by lovepoem** [comment]
@billowqiu  I'll deploy a snapshot jar tonight . Then merge the pr  https://github.com/apache/incubator-dubbo-samples/pull/8

**Comment by billowqiu** [comment]
这个demo能跑去来吗？我这边直接就抛异常了
Exception in thread "main" java.lang.IllegalStateException: No such extension com.alibaba.dubbo.rpc.Protocol by name nthrift, possible causes: 
(1) com.alibaba.dubbo.rpc.protocol.http.HttpProtocol:
java.lang.IllegalStateException: Failed to load extension class(interface: interface com.alibaba.dubbo.rpc.Protocol, class line: com.alibaba.dubbo.rpc.protocol.http.HttpProtocol) in jar:file:/C:/Users/qiutao/.m2/repository/com/alibaba/dubbo/2.6.5/dubbo-2.6.5.jar!/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.Protocol, cause: org/springframework/remoting/httpinvoker/HttpInvokerRequestExecutor
java.lang.IllegalStateException: Failed to load extension class(interface: interface com.alibaba.dubbo.rpc.Protocol, class line: com.alibaba.dubbo.rpc.protocol.http.HttpProtocol) in jar:file:/C:/Users/qiutao/.m2/repository/com/alibaba/dubbo/2.6.5/dubbo-2.6.5.jar!/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.Protocol, cause: org/springframework/remoting/httpinvoker/HttpInvokerRequestExecutor
	at com.alibaba.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:634)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:604)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:585)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:561)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtensionClass(ExtensionLoader.java:549)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.hasExtension(ExtensionLoader.java:333)
	at com.alibaba.dubbo.config.spring.schema.DubboBeanDefinitionParser.parse(DubboBeanDefinitionParser.java:189)
	at com.alibaba.dubbo.config.spring.schema.DubboBeanDefinitionParser.parse(DubboBeanDefinitionParser.java:417)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1410)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1400)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:172)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:142)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:515)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.dubbo.samples.rpc.nativethrift.ThriftProvider.main(ThriftProvider.java:26)
Caused by: java.lang.NoClassDefFoundError: org/springframework/remoting/httpinvoker/HttpInvokerRequestExecutor
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:631)

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/51247272-975ab000-19c7-11e9-8092-9cbe8756ad18.png)
Yes ,  I can run it in idea , and is successful
